In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

Using the Corona Virus Data Sets given , Create an Interactive Dashboard along with the
answers to the below given problem statements.

1. What is the proportionality of genders in regard to no of affected people & dead people.
2. Highlight the time duration takes from the day admitted to the death.
3. Excluding Wuhan, report the disease transmission in other provinces.
4. Which symptom becomes the most common of the dead people?
5. Which age people are most likely to get caught Covid-19?

## Dealing with Null values of Relevant columns based on problem statements

In [113]:
df=pd.read_csv("COVID19_open_line_list_cleaned_1.csv")

In [88]:
df.head()

,ID,age,sex,city,province,country,wuhan(0)_not_wuhan(1),latitude,longitude,geo_resolution,...,outcome,date_death_or_discharge,notes_for_discussion,location,admin3,admin2,admin1,country_new,admin_id,data_moderator_initials
0,1.0,30.0,male,"Chaohu City, Hefei City",Anhui,China,1.0,31.646960,117.716600,admin3,...,NaN,NaN,NaN,NaN,Chaohu City,Hefei City,Anhui,China,340181,NaN
1,2.0,47.0,male,"Baohe District, Hefei City",Anhui,China,1.0,31.778630,117.331900,admin3,...,NaN,NaN,NaN,NaN,Baohe District,Hefei City,Anhui,China,340111,NaN
2,3.0,49.0,male,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point,...,NaN,NaN,NaN,High-Tech Zone,Shushan District,Hefei City,Anhui,China,340104,NaN
3,4.0,47.0,female,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point,...,NaN,NaN,NaN,High-Tech Zone,Shushan District,Hefei City,Anhui,China,340104,NaN
4,5.0,50.0,female,"Feidong County, Hefei City",Anhui,China,1.0,32.001230,117.568100,admin3,...,NaN,NaN,NaN,NaN,Feidong County,Hefei City,Anhui,China,340122,NaN

In [89]:
df.columns

Index(['ID', 'age', 'sex', 'city', 'province', 'country',
       'wuhan(0)_not_wuhan(1)', 'latitude', 'longitude', 'geo_resolution',
       'date_onset_symptoms', 'date_admission_hospital', 'date_confirmation',
       'symptoms', 'lives_in_Wuhan', 'travel_history_dates',
       'travel_history_location', 'reported_market_exposure',
       'additional_information', 'chronic_disease_binary', 'chronic_disease',
       'source', 'sequence_available', 'outcome', 'date_death_or_discharge',
       'notes_for_discussion', 'location', 'admin3', 'admin2', 'admin1',
       'country_new', 'admin_id', 'data_moderator_initials'],
      dtype='object')

In [11]:
df

,ID,age,sex,city,province,country,wuhan(0)_not_wuhan(1),latitude,longitude,geo_resolution,...,admin3,admin2,admin1,country_new,admin_id,data_moderator_initials,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,1.0,30,male,"Chaohu City, Hefei City",Anhui,China,1.0,31.646960,117.716600,admin3,...,Chaohu City,Hefei City,Anhui,China,340181,NaN,NaN,NaN,NaN,NaN
1,2.0,47,male,"Baohe District, Hefei City",Anhui,China,1.0,31.778630,117.331900,admin3,...,Baohe District,Hefei City,Anhui,China,340111,NaN,NaN,NaN,NaN,NaN
2,3.0,49,male,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point,...,Shushan District,Hefei City,Anhui,China,340104,NaN,NaN,NaN,NaN,NaN
3,4.0,47,female,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point,...,Shushan District,Hefei City,Anhui,China,340104,NaN,NaN,NaN,NaN,NaN
4,5.0,50,female,"Feidong County, Hefei City",Anhui,China,1.0,32.001230,117.568100,admin3,...,Feidong County,Hefei City,Anhui,China,340122,NaN,NaN,NaN,NaN,NaN
5,6.0,NaN,NaN,Lu'an City,Anhui,China,1.0,31.759410,116.315100,admin2,...,NaN,Lu'an City,Anhui,China,341500,NaN,NaN,NaN,NaN,NaN
6,7.0,42,female,Fuyang City,Anhui,China,1.0,32.918800,115.703600,admin2,...,NaN,Fuyang City,Anhui,China,341200,NaN,NaN,NaN,NaN,NaN
7,8.0,NaN,female,Huaibei City,Anhui,China,1.0,33.727220,116.742400,admin2,...,NaN,Huaibei City,Anhui,China,340600,NaN,NaN,NaN,NaN,NaN
8,9.0,59,female,Huainan City,Anhui,China,1.0,32.757380,116.734000,admin2,...,NaN,Huainan City,Anhui,China,340400,NaN,NaN,NaN,NaN,NaN
9,10.0,30,male,Hefei City,Anhui,China,1.0,31.794440,117.342800,admin2,...,NaN,Hefei City,Anhui,China,340100,NaN,NaN,NaN,NaN,NaN
10,11.0,NaN,NaN,Lu'an City,Anhui,China,1.0,31.759410,116.315100,admin2,...,NaN,Lu'an City,Anhui,China,341500,NaN,NaN,NaN,NaN,NaN
11,12.0,39,male,Fuyang City,Anhui,China,1.0,32.918800,115.703600,admin2,...,NaN,Fuyang City,Anhui,China,341200,NaN,NaN,NaN,NaN,NaN
12,13.0,NaN,NaN,Anqing City,Anhui,China,1.0,30.611220,116.595600,admin2,...,NaN,Anqing City,Anhui,China,340800,NaN,NaN,NaN,NaN,NaN
13,14.0,38,female,Chizhou City,Anhui,China,1.0,30.285250,117.365800,admin2,...,NaN,Chizhou City,Anhui,China,341700,NaN,NaN,NaN,NaN,NaN
14,15.0,45,male,Bengbu City,Anhui,China,1.0,33.109010,117.326000,admin2,...,NaN,Bengbu City,Anhui,China,340300,NaN,NaN,NaN,NaN,NaN
15,16.0,NaN,NaN,Changping District,Beijing,China,1.0,40.207890,116.206300,admin3,...,Changping District,Beijing,Beijing,China,110114,NaN,NaN,NaN,NaN,NaN
16,17.0,NaN,NaN,Changping District,Beijing,China,1.0,40.207890,116.206300,admin3,...,Changping District,Beijing,Beijing,China,110114,NaN,NaN,NaN,NaN,NaN
17,18.0,33,female,Changping District,Beijing,China,1.0,40.207890,116.206300,admin3,...,Changping District,Beijing,Beijing,China,110114,NaN,NaN,NaN,NaN,NaN
18,19.0,NaN,female,Daxing District,Beijing,China,1.0,39.642380,116.417200,admin3,...,Daxing District,Beijing,Beijing,China,110115,NaN,NaN,NaN,NaN,NaN
19,20.0,NaN,NaN,Daxing District,Beijing,China,1.0,39.642380,116.417200,admin3,...,Daxing District,Beijing,Beijing,China,110115,NaN,NaN,NaN,NaN,NaN
20,21.0,37,male,Fengtai District,Beijing,China,1.0,39.830600,116.249900,admin3,...,Fengtai District,Beijing,Beijing,China,110106,NaN,NaN,NaN,NaN,NaN
21,22.0,39,male,Haidian District,Beijing,China,1.0,40.021860,116.228500,admin3,...,Haidian District,Beijing,Beijing,China,110108,NaN,NaN,NaN,NaN,NaN
22,23.0,32,female,Haidian District,Beijing,China,1.0,40.021860,116.228500,admin3,...,Haidian District,Beijing,Beijing,China,110108,NaN,NaN,NaN,NaN,NaN
23,24.0,45,male,Shijingshan District,Beijing,China,1.0,39.927150,116.173700,admin3,...,Shijingshan District,Beijing,Beijing,China,110107,NaN,NaN,NaN,NaN,NaN
24,25.0,45,male,Shijingshan District,Beijing,China,1.0,39.927150,116.173700,admin3,...,Shijingshan District,Beijing,Beijing,China,110107,NaN,NaN,NaN,NaN,NaN
25,26.0,18,female,Tongzhou District,Beijing,China,1.0,39.802920,116.736300,admin3,...,Tongzhou District,Beijing,Beijing,China,110112,NaN,NaN,NaN,NaN,NaN
26,27.0,56,female,Xicheng District,Beijing,China,1.0,39.910930,116.359100,admin3,...,Xicheng District,Beijing,Beijing,China,110102,NaN,NaN,NaN,NaN,NaN
27,28.0,42,male,Xicheng District,Beijing,China,1.0,39.910930,116.359100,admin3,...,Xicheng District,Beijing,Beijing,China,110102,NaN,NaN,NaN,NaN,NaN
28,29.0,33,female,NaN,Beijing,China,1.0,40.185350,116.415100,admin1,...,NaN,NaN,Beijing,China,110000,NaN,NaN,NaN,NaN,NaN
29,30.0,NaN,NaN,Haidian District,Beijing,China,1.0,40.021860,116.228500,admin3,...,Haidian District,Beijing,Beijing,China,110108,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13144,13450.0,45,male,Maramures,NaN,Romania,1.0,47.656844,23.582194,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13145,13451.0,38,female,Timisoara,NaN,Romania,1.0,45.759722,21.230000,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13146,13452.0,NaN,NaN,Oslo,NaN,Norway,1.0,59.914820,10.754192,point,...,NaN,NaN,TBD,Norway,TBD,NaN,NaN,NaN,NaN,NaN
13147,13453.0,NaN,NaN,Oslo,NaN,Norway,1.0,59.914820,10.754192,point,...,NaN,NaN,TBD,Norway,TBD,NaN,NaN,NaN,NaN,NaN
13148,13454.0,NaN,NaN,Baerum,NaN,Norway,1.0,59.938333,10.506667,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13149,13455.0,39,female,Siauliai,NaN,Lithuania,1.0,55.933333,23.316667,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13150,13456.0,NaN,female,Ben Gurion Airport,NaN,Israel,1.0,32.009444,34.882778,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13151,13457.0,NaN,NaN,NaN,NaN,Israel,1.0,31.471090,35.015270,admin0,...,NaN,NaN,NaN,Israel,111,NaN,NaN,NaN,NaN,NaN
13152,13458.0,NaN,female,NaN,NaN,Israel,1.0,31.471090,35.015270,admin0,...,NaN,NaN,NaN,Israel,111,NaN,NaN,NaN,NaN,NaN
13153,13459.0,40-49,female,Sagamihara City,Kanagawa,Japan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13154,13460.0,20-29,male,Sagamihara City,Kanagawa,Japan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13155,13461.0,60-69,male,Shizuoka City,Shizuoka,Japan,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13156,13462.0,80-89,female,Setana,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13157,13463.0,0-10,male,Chitose,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13158,13464.0,80-89,male,Fukagawa,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13159,13465.0,60-69,female,Kamikawa,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13160,13466.0,60-69,male,Nakafurano,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13161,13467.0,60-69,male,Kitami City,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13162,13468.0,60-69,female,Kitami City,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13163,13469.0,40-49,male,Kushiro,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13164,13470.0,70-79,male,Kushiro,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13165,13471.0,60-69,female,Sapporo City,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13166,13472.0,60-69,female,Sapporo City,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13167,13473.0,60-69,male,Sapporo City,Hokkaido,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13168,13474.0,50-59,male,NaN,Ishikawa,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13169,13475.0,60-69,male,Nagoya City,Aichi Prefecture,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13170,13476.0,40-49,female,NaN,Osaka,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13171,13477.0,0-10,female,NaN,Osaka,Japan,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13172,13478.0,NaN,female,Amsterdam,NaN,Netherlands,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13173,13479.0,NaN,female,"Jose Joaquin de Olmedo Airport, Guayaquil",Guayas,Ecuador,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.drop(axis=1,columns=[ 'Unnamed: 33','Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36'],inplace=True)

In [16]:
df.head()

,ID,age,sex,city,province,country,wuhan(0)_not_wuhan(1),latitude,longitude,geo_resolution,...,outcome,date_death_or_discharge,notes_for_discussion,location,admin3,admin2,admin1,country_new,admin_id,data_moderator_initials
0,1.0,30,male,"Chaohu City, Hefei City",Anhui,China,1.0,31.646960,117.716600,admin3,...,NaN,NaN,NaN,NaN,Chaohu City,Hefei City,Anhui,China,340181,NaN
1,2.0,47,male,"Baohe District, Hefei City",Anhui,China,1.0,31.778630,117.331900,admin3,...,NaN,NaN,NaN,NaN,Baohe District,Hefei City,Anhui,China,340111,NaN
2,3.0,49,male,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point,...,NaN,NaN,NaN,High-Tech Zone,Shushan District,Hefei City,Anhui,China,340104,NaN
3,4.0,47,female,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point,...,NaN,NaN,NaN,High-Tech Zone,Shushan District,Hefei City,Anhui,China,340104,NaN
4,5.0,50,female,"Feidong County, Hefei City",Anhui,China,1.0,32.001230,117.568100,admin3,...,NaN,NaN,NaN,NaN,Feidong County,Hefei City,Anhui,China,340122,NaN

In [23]:
df['age'].value_counts()

33.0    29
50.0    29
49.0    27
30.0    26
35.0    26
42.0    24
43.0    24
47.0    24
56.0    23
41.0    23
39.0    23
38.0    23
45.0    23
37.0    23
55.0    22
28.0    20
51.0    20
52.0    19
25.0    19
40.0    19
36.0    19
32.0    19
24.0    19
29.0    19
60.0    19
27.0    18
44.0    17
34.0    17
64.0    17
54.0    16
        ..
16.0     5
75.0     5
80.0     5
78.0     5
17.0     5
2.0      4
15.0     4
8.0      4
71.0     4
4.0      3
7.0      3
9.0      3
88.0     3
82.0     3
1.0      2
12.0     2
19.0     2
79.0     2
18.0     2
11.0     2
5.0      2
74.0     2
76.0     2
84.0     2
96.0     1
94.0     1
3.0      1
81.0     1
83.0     1
87.0     1
Name: age, Length: 85, dtype: int64

In [28]:
df['age'].mean()

44.05711422845691

In [68]:
df.dropna(how='all',inplace=True)

In [83]:
df.to_csv('COVID19_open_line_list_cleaned_4.csv',index=False)

In [67]:
df.dropna(how='any',subset=['age','sex','province'],inplace=True)

In [71]:
df

,ID,age,sex,city,province,country,wuhan(0)_not_wuhan(1),latitude,longitude,geo_resolution,...,outcome,date_death_or_discharge,notes_for_discussion,location,admin3,admin2,admin1,country_new,admin_id,data_moderator_initials
0,1.0,30.0,male,"Chaohu City, Hefei City",Anhui,China,1.0,31.646960,117.716600,admin3,...,NaN,NaN,NaN,NaN,Chaohu City,Hefei City,Anhui,China,340181,NaN
1,2.0,47.0,male,"Baohe District, Hefei City",Anhui,China,1.0,31.778630,117.331900,admin3,...,NaN,NaN,NaN,NaN,Baohe District,Hefei City,Anhui,China,340111,NaN
2,3.0,49.0,male,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point,...,NaN,NaN,NaN,High-Tech Zone,Shushan District,Hefei City,Anhui,China,340104,NaN
3,4.0,47.0,female,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point,...,NaN,NaN,NaN,High-Tech Zone,Shushan District,Hefei City,Anhui,China,340104,NaN
4,5.0,50.0,female,"Feidong County, Hefei City",Anhui,China,1.0,32.001230,117.568100,admin3,...,NaN,NaN,NaN,NaN,Feidong County,Hefei City,Anhui,China,340122,NaN
6,7.0,42.0,female,Fuyang City,Anhui,China,1.0,32.918800,115.703600,admin2,...,NaN,NaN,NaN,NaN,NaN,Fuyang City,Anhui,China,341200,NaN
8,9.0,59.0,female,Huainan City,Anhui,China,1.0,32.757380,116.734000,admin2,...,NaN,NaN,NaN,NaN,NaN,Huainan City,Anhui,China,340400,NaN
9,10.0,30.0,male,Hefei City,Anhui,China,1.0,31.794440,117.342800,admin2,...,NaN,NaN,NaN,NaN,NaN,Hefei City,Anhui,China,340100,NaN
11,12.0,39.0,male,Fuyang City,Anhui,China,1.0,32.918800,115.703600,admin2,...,NaN,NaN,NaN,NaN,NaN,Fuyang City,Anhui,China,341200,NaN
13,14.0,38.0,female,Chizhou City,Anhui,China,1.0,30.285250,117.365800,admin2,...,NaN,NaN,NaN,NaN,NaN,Chizhou City,Anhui,China,341700,NaN
14,15.0,45.0,male,Bengbu City,Anhui,China,1.0,33.109010,117.326000,admin2,...,NaN,NaN,NaN,NaN,NaN,Bengbu City,Anhui,China,340300,NaN
17,18.0,33.0,female,Changping District,Beijing,China,1.0,40.207890,116.206300,admin3,...,NaN,NaN,NaN,NaN,Changping District,Beijing,Beijing,China,110114,NaN
20,21.0,37.0,male,Fengtai District,Beijing,China,1.0,39.830600,116.249900,admin3,...,NaN,NaN,NaN,NaN,Fengtai District,Beijing,Beijing,China,110106,NaN
21,22.0,39.0,male,Haidian District,Beijing,China,1.0,40.021860,116.228500,admin3,...,NaN,NaN,NaN,NaN,Haidian District,Beijing,Beijing,China,110108,NaN
22,23.0,32.0,female,Haidian District,Beijing,China,1.0,40.021860,116.228500,admin3,...,NaN,NaN,NaN,NaN,Haidian District,Beijing,Beijing,China,110108,NaN
23,24.0,45.0,male,Shijingshan District,Beijing,China,1.0,39.927150,116.173700,admin3,...,NaN,NaN,NaN,NaN,Shijingshan District,Beijing,Beijing,China,110107,NaN
24,25.0,45.0,male,Shijingshan District,Beijing,China,1.0,39.927150,116.173700,admin3,...,NaN,NaN,NaN,NaN,Shijingshan District,Beijing,Beijing,China,110107,NaN
25,26.0,18.0,female,Tongzhou District,Beijing,China,1.0,39.802920,116.736300,admin3,...,NaN,NaN,NaN,NaN,Tongzhou District,Beijing,Beijing,China,110112,NaN
26,27.0,56.0,female,Xicheng District,Beijing,China,1.0,39.910930,116.359100,admin3,...,NaN,NaN,NaN,NaN,Xicheng District,Beijing,Beijing,China,110102,NaN
27,28.0,42.0,male,Xicheng District,Beijing,China,1.0,39.910930,116.359100,admin3,...,NaN,NaN,NaN,NaN,Xicheng District,Beijing,Beijing,China,110102,NaN
28,29.0,33.0,female,NaN,Beijing,China,1.0,40.185350,116.415100,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,Beijing,China,110000,NaN
37,38.0,44.0,male,NaN,Beijing,China,1.0,40.185350,116.415100,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,Beijing,China,110000,NaN
38,39.0,65.0,male,NaN,Beijing,China,1.0,40.185350,116.415100,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,Beijing,China,110000,NaN
39,40.0,21.0,male,NaN,Beijing,China,1.0,40.185350,116.415100,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,Beijing,China,110000,NaN
40,41.0,41.0,male,NaN,Beijing,China,1.0,40.185350,116.415100,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,Beijing,China,110000,NaN
55,56.0,44.0,female,Wushan County,Chongqing,China,1.0,31.117740,109.896200,admin3,...,discharged,29.01.2020,NaN,NaN,Wushan County,Chongqing County,Chongqing,China,500237,NaN
78,79.0,30.0,female,Fuzhou City,Fujian,China,1.0,26.051960,119.178900,admin2,...,NaN,NaN,NaN,NaN,NaN,Fuzhou City,Fujian,China,350100,NaN
79,80.0,70.0,male,Fuzhou City,Fujian,China,1.0,26.051960,119.178900,admin2,...,NaN,NaN,NaN,NaN,NaN,Fuzhou City,Fujian,China,350100,NaN
80,81.0,43.0,female,Ningde City,Fujian,China,1.0,26.976740,119.474500,admin2,...,NaN,NaN,NaN,NaN,NaN,Ningde City,Fujian,China,350900,NaN
82,83.0,31.0,male,Xiamen City,Fujian,China,1.0,24.675950,118.113800,admin2,...,NaN,NaN,NaN,NaN,NaN,Xiamen City,Fujian,China,350200,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11798,12104.0,55.0,male,Amiens,Hauts-de-France,France,1.0,49.898541,2.214597,point,...,NaN,NaN,NaN,Amiens,NaN,Somme,Hauts-de-France,France,47,NaN
11799,12105.0,36.0,male,Strasbourg,Grand Est,France,1.0,48.568847,7.622951,point,...,NaN,NaN,NaN,Strasbourg,NaN,Bas-Rhin,Grand Est,France,35,NaN
11800,12106.0,60.0,male,Paris,Ile-de-France,France,1.0,48.856600,2.352200,point,...,death,26.02.2020,NaN,Paris,NaN,NaN,Ile-de-France,France,8,NaN
11804,12110.0,41.0,male,NaN,North Rhine-Westphalia,Germany,1.0,51.466667,7.550000,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,North Rhine-Westphalia,Germany,TBD,NaN
11806,12112.0,47.0,male,Dusseldorf University Hospital,North Rhine-Westphalia,Germany,1.0,51.197415,6.786893,point,...,NaN,NaN,NaN,Dusseldorf University Hospital,NaN,NaN,North Rhine-Westphalia,Germany,TBD,NaN
11807,12113.0,20.0,male,Prigoria,Gorj,Romania,1.0,45.066667,23.683333,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12232,12538.0,21.0,Female,Hong Kong,Hong Kong,China,1.0,22.380740,114.132400,admin 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Hong Kong,China,700000,NaN
12233,12539.0,16.0,Male,Hong Kong,Hong Kong,China,1.0,22.380740,114.132400,admin 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Hong Kong,China,700000,NaN
12234,12540.0,80.0,Male,Hong Kong,Hong Kong,China,1.0,22.380740,114.132400,admin 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Hong Kong,China,700000,NaN
12236,12542.0,33.0,Male,Hong Kong,Hong Kong,China,1.0,22.380740,114.132400,admin 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Hong Kong,China,700000,NaN
12237,12543.0,55.0,Female,Hong Kong,Hong Kong,China,1.0,22.380740,114.132400,admin 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Hong Kong,China,700000,NaN
12238,12544.0,24.0,Male,Hong Kong,Hong Kong,China,1.0,22.380740,114.132400,admin 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Hong Kong,China,700000,NaN
12239,12545.0,60.0,Female,Hong Kong,Hong Kong,China,1.0,22.380740,114.132400,admin 1,...,NaN,NaN,NaN,NaN,NaN,NaN,Hong Kong,China,700000,NaN
12295,12601.0,77.0,male,Beirut,Beirut,Lebanon,1.0,33.886940,35.513060,point,...,NaN,NaN,NaN,Beirut,NaN,NaN,Beirut,Lebanon,3,NaN
12313,12619.0,54.0,female,Bamrasnaradura Hospital,Nonthaburi,Thailand,1.0,13.853800,100.522800,point,...,NaN,NaN,NaN,Bamrasnaradura Hospital,NaN,Mueang Nonthaburi District,Nonthaburi,Thailand,490,NaN
12315,12621.0,65.0,male,Bamrasnaradura Hospital,Nonthaburi,Thailand,1.0,13.853800,100.522800,point,...,NaN,NaN,NaN,Bamrasnaradura Hospital,NaN,Mueang Nonthaburi District,Nonthaburi,Thailand,490,NaN
12316,12622.0,62.0,female,Bamrasnaradura Hospital,Nonthaburi,Thailand,1.0,13.853800,100.522800,point,...,NaN,NaN,NaN,Bamrasnaradura Hospital,NaN,Mueang Nonthaburi District,Nonthaburi,Thailand,490,NaN
12317,12623.0,8.0,male,Bamrasnaradura Hospital,Nonthaburi,Thailand,1.0,13.853800,100.522800,point,...,NaN,NaN,NaN,Bamrasnaradura Hospital,NaN,Mueang Nonthaburi District,Nonthaburi,Thailand,490,NaN
12320,12626.0,29.0,male,Bamrasnaradura Hospital,Nonthaburi,Thailand,1.0,13.853800,100.522800,point,...,NaN,NaN,NaN,Bamrasnaradura Hospital,NaN,Mueang Nonthaburi District,Nonthaburi,Thailand,490,NaN
12587,12893.0,18.0,male,NaN,Castilla y Leon,Spain,1.0,41.767612,-4.780517,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,Castilla y Leon,Spain,5,NaN
12588,12894.0,28.0,male,NaN,Castilla y Leon,Spain,1.0,41.767612,-4.780517,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,Castilla y Leon,Spain,5,NaN
12589,12895.0,72.0,female,Alassio,Liguria,Italy,1.0,44.000000,8.166667,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12590,12896.0,54.0,male,La Spezia,Liguria,Italy,1.0,44.100000,9.816667,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12591,12897.0,43.0,male,Torricella,Puglia,Italy,1.0,40.354482,17.500312,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12592,12898.0,4.0,female,Castiglione d'Adda,Lombardia,Italy,1.0,45.216670,9.683333,point,...,NaN,NaN,NaN,Castiglione d'Adda,NaN,NaN,Lombardia,Italy,10,NaN
12593,12899.0,10.0,male,"Soresina, Cremona",Lombardia,Italy,1.0,45.287216,9.857652,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12594,12900.0,10.0,male,"San Rocco al Porto, Lodi",Lombardia,Italy,1.0,45.150000,9.700000,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12989,13295.0,24.0,female,"Caserta, Ruviano",Campania,Italy,1.0,41.216667,14.416667,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13115,13421.0,26.0,male,NaN,Aargau,Switzerland,1.0,47.083333,8.000000,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,Aargau,Switzerland,TBD,NaN
13140,13446.0,23.0,male,NaN,Basel,Switzerland,1.0,47.566667,7.600000,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
df.columns

Index(['ID', 'age', 'sex', 'city', 'province', 'country',
       'wuhan(0)_not_wuhan(1)', 'latitude', 'longitude', 'geo_resolution',
       'date_onset_symptoms', 'date_admission_hospital', 'date_confirmation',
       'symptoms', 'lives_in_Wuhan', 'travel_history_dates',
       'travel_history_location', 'reported_market_exposure',
       'additional_information', 'chronic_disease_binary', 'chronic_disease',
       'source', 'sequence_available', 'outcome', 'date_death_or_discharge',
       'notes_for_discussion', 'location', 'admin3', 'admin2', 'admin1',
       'country_new', 'admin_id', 'data_moderator_initials'],
      dtype='object')

In [73]:
df['city'].fillna('None',inplace=True)

In [74]:
df['country'].fillna('None',inplace=True)

In [76]:
df['latitude'].fillna(0,inplace=True)

In [77]:
df['longitude'].fillna(0,inplace=True)

In [79]:
df['geo_resolution'].fillna('None',inplace=True)

In [81]:
df['date_onset_symptoms']=df['date_onset_symptoms'].replace('end of December 2019',np.nan)

In [84]:
df1=df[['ID', 'age', 'sex', 'city', 'province', 'country','wuhan(0)_not_wuhan(1)', 'latitude', 'longitude', 'geo_resolution']]

## Extraction and more Cleaning of relevant columns for a given problem statements

In [86]:
df1.head()

,ID,age,sex,city,province,country,wuhan(0)_not_wuhan(1),latitude,longitude,geo_resolution
0,1.0,30.0,male,"Chaohu City, Hefei City",Anhui,China,1.0,31.646960,117.716600,admin3
1,2.0,47.0,male,"Baohe District, Hefei City",Anhui,China,1.0,31.778630,117.331900,admin3
2,3.0,49.0,male,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point
3,4.0,47.0,female,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point
4,5.0,50.0,female,"Feidong County, Hefei City",Anhui,China,1.0,32.001230,117.568100,admin3

In [90]:
df1.dtypes

ID                       float64
age                      float64
sex                       object
city                      object
province                  object
country                   object
wuhan(0)_not_wuhan(1)    float64
latitude                 float64
longitude                float64
geo_resolution            object
dtype: object

In [91]:
df.columns

Index(['ID', 'age', 'sex', 'city', 'province', 'country',
       'wuhan(0)_not_wuhan(1)', 'latitude', 'longitude', 'geo_resolution',
       'date_onset_symptoms', 'date_admission_hospital', 'date_confirmation',
       'symptoms', 'lives_in_Wuhan', 'travel_history_dates',
       'travel_history_location', 'reported_market_exposure',
       'additional_information', 'chronic_disease_binary', 'chronic_disease',
       'source', 'sequence_available', 'outcome', 'date_death_or_discharge',
       'notes_for_discussion', 'location', 'admin3', 'admin2', 'admin1',
       'country_new', 'admin_id', 'data_moderator_initials'],
      dtype='object')

In [116]:
df2=df[['city', 'province', 'country','wuhan(0)_not_wuhan(1)','symptoms','lives_in_Wuhan','date_admission_hospital', 'outcome', 'date_death_or_discharge']]

In [117]:
df2.head()

,city,province,country,wuhan(0)_not_wuhan(1),symptoms,lives_in_Wuhan,date_admission_hospital,outcome,date_death_or_discharge
0,"Chaohu City, Hefei City",Anhui,China,1.0,NaN,yes,20.01.2020,NaN,NaN
1,"Baohe District, Hefei City",Anhui,China,1.0,NaN,no,21.01.2020,NaN,NaN
2,"High-Tech Zone, Hefei City",Anhui,China,1.0,NaN,no,20.01.2020,NaN,NaN
3,"High-Tech Zone, Hefei City",Anhui,China,1.0,NaN,no,20.01.2020,NaN,NaN
4,"Feidong County, Hefei City",Anhui,China,1.0,NaN,no,21.01.2020,NaN,NaN

In [118]:
df2['symptoms'].fillna('None',inplace=True)

C:\Users\Lenovo\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [119]:
df2.head()

,city,province,country,wuhan(0)_not_wuhan(1),symptoms,lives_in_Wuhan,date_admission_hospital,outcome,date_death_or_discharge
0,"Chaohu City, Hefei City",Anhui,China,1.0,None,yes,20.01.2020,NaN,NaN
1,"Baohe District, Hefei City",Anhui,China,1.0,None,no,21.01.2020,NaN,NaN
2,"High-Tech Zone, Hefei City",Anhui,China,1.0,None,no,20.01.2020,NaN,NaN
3,"High-Tech Zone, Hefei City",Anhui,China,1.0,None,no,20.01.2020,NaN,NaN
4,"Feidong County, Hefei City",Anhui,China,1.0,None,no,21.01.2020,NaN,NaN

In [121]:
df2.dropna(subset=['outcome'],inplace=True)

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [130]:
df2['outcome'].value_counts()

discharge                                         81
stable                                            34
death                                             12
recovered                                          1
critical condition, intubated as of 14.02.2020     1
05.02.2020                                         1
Name: outcome, dtype: int64

In [126]:
df2['outcome'].replace("died",'death',inplace=True)

C:\Users\Lenovo\Anaconda3\lib\site-packages\pandas\core\generic.py:6586: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [129]:
df2['outcome'].replace("Discharged",'discharge',inplace=True)

In [136]:
df2.drop(index=df[df['outcome']=='05.02.2020 '].index,inplace=True)

In [137]:
df2.head()

,city,province,country,wuhan(0)_not_wuhan(1),symptoms,lives_in_Wuhan,date_admission_hospital,outcome,date_death_or_discharge
18,Daxing District,Beijing,China,1.0,"fatigue, fever, headache",no,08.01.2020,discharge,24.01.2020
55,Wushan County,Chongqing,China,1.0,"fatigue, fever",NaN,15.01.2020,discharge,29.01.2020
161,Fangchenggang City,Guangxi,China,1.0,discomfort,no,23.01.2020,discharge,28.01.2020
175,Suihua City,Heilongjiang,China,1.0,None,NaN,NaN,death,23.01.2020
185,Hong Kong,Hong Kong,China,1.0,"cough, fever",yes,21.01.2020,death,NaN

In [138]:
df2.columns

Index(['city', 'province', 'country', 'wuhan(0)_not_wuhan(1)', 'symptoms',
       'lives_in_Wuhan', 'date_admission_hospital', 'outcome',
       'date_death_or_discharge'],
      dtype='object')

In [140]:
df2.dtypes

city                        object
province                    object
country                     object
wuhan(0)_not_wuhan(1)      float64
symptoms                    object
lives_in_Wuhan              object
date_admission_hospital     object
outcome                     object
date_death_or_discharge     object
dtype: object

In [142]:
df2['date_admission_hospital']=pd.to_datetime(df2['date_admission_hospital'],format='%d.%m.%Y')

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [146]:
df2['date_death_or_discharge'].value_counts()

26.02.2020    8
17.02.2020    6
18.02.2020    5
22.02.2020    5
10.02.2020    4
12.02.2020    4
25.02.2020    4
05.02.2020    4
27.02.2020    3
14.02.2020    3
09.02.2020    3
02.02.2020    3
23.02.2020    2
24.02.2020    2
20.02.2020    2
13.02.2020    2
16.02.2020    2
08.02.2020    2
19.02.2020    2
28.01.2020    2
30.01.2020    1
29.01.2020    1
17.01.2020    1
discharge     1
21.02.2020    1
03.02.2020    1
07.02.2020    1
31.01.2020    1
01.02.2020    1
06.02.2020    1
02.02.2021    1
23.01.2020    1
28.02.2020    1
15.02.2020    1
27.01.2020    1
15.01.2020    1
24.01.2020    1
Name: date_death_or_discharge, dtype: int64

In [148]:
df2.drop(index=df2[df2['date_death_or_discharge']=='discharge'].index,inplace=True)

In [149]:
df2['date_death_or_discharge'].value_counts()

26.02.2020    8
17.02.2020    6
18.02.2020    5
22.02.2020    5
10.02.2020    4
12.02.2020    4
25.02.2020    4
05.02.2020    4
02.02.2020    3
14.02.2020    3
09.02.2020    3
27.02.2020    3
13.02.2020    2
24.02.2020    2
16.02.2020    2
08.02.2020    2
23.02.2020    2
19.02.2020    2
28.01.2020    2
20.02.2020    2
29.01.2020    1
17.01.2020    1
30.01.2020    1
23.01.2020    1
21.02.2020    1
07.02.2020    1
31.01.2020    1
01.02.2020    1
06.02.2020    1
03.02.2020    1
02.02.2021    1
28.02.2020    1
15.02.2020    1
27.01.2020    1
15.01.2020    1
24.01.2020    1
Name: date_death_or_discharge, dtype: int64

In [151]:
df2['date_death_or_discharge']=pd.to_datetime(df2['date_death_or_discharge'],format='%d.%m.%Y')

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [153]:
df2.dtypes

city                               object
province                           object
country                            object
wuhan(0)_not_wuhan(1)             float64
symptoms                           object
lives_in_Wuhan                     object
date_admission_hospital    datetime64[ns]
outcome                            object
date_death_or_discharge    datetime64[ns]
dtype: object

In [154]:
df1.dtypes

ID                       float64
age                      float64
sex                       object
city                      object
province                  object
country                   object
wuhan(0)_not_wuhan(1)    float64
latitude                 float64
longitude                float64
geo_resolution            object
dtype: object

In [155]:
df1.to_csv('COVID19_open_line_list_cleaned_final_part_1.csv',index=False)

In [156]:
df2.to_csv('COVID19_open_line_list_cleaned_final_part_2.csv',index=False)

In [157]:
df1.head()

,ID,age,sex,city,province,country,wuhan(0)_not_wuhan(1),latitude,longitude,geo_resolution
0,1.0,30.0,male,"Chaohu City, Hefei City",Anhui,China,1.0,31.646960,117.716600,admin3
1,2.0,47.0,male,"Baohe District, Hefei City",Anhui,China,1.0,31.778630,117.331900,admin3
2,3.0,49.0,male,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point
3,4.0,47.0,female,"High-Tech Zone, Hefei City",Anhui,China,1.0,31.828313,117.224844,point
4,5.0,50.0,female,"Feidong County, Hefei City",Anhui,China,1.0,32.001230,117.568100,admin3

In [161]:
df1[df1['country'].isnull()]

Empty DataFrame
Columns: [ID, age, sex, city, province, country, wuhan(0)_not_wuhan(1), latitude, longitude, geo_resolution]
Index: []